src/components/awards-leaderboard-ui.js
src/helpers/leaderboardRoutes.js
src/services/awards-leaderboard-service.js

* Add a couple more routes that will be used soon

Retrieve max ten users from API call

---

src/components/awards-leaderboard-ui.js
src/components/leaderboard-row.js

* Do some styling for my rank - clean the border

US113510 Add my awards at the top of the list

---

polymer.json

We need an extra dependency on the images folder

Add images to build

---

lang/en.json
src/components/awards-leaderboard-ui.js
src/components/leaderboard-row.js
src/constants/constants.js
src/helpers/leaderboardRoutes.js
src/services/awards-leaderboard-service.js

* If sorted by credits, display that instead of award count
Related to Steve's and my PR
https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/9148/overview

US113505 Use config setting to determine sort order

---

src/components/leaderboard-row.js

Still more to do
This is just adding in a bit more padding.
Until I get the updated styles from design

Address some styling feedback

---

src/components/award-issued.js
src/components/awards-leaderboard-ui.js
src/components/leaderboard-row.js
src/helpers/leaderboardRoutes.js
src/services/awards-leaderboard-service.js

Get awards dialog to display with awards details.
This is using the same dialog that displays within other parts of the LMS - However, locally, it wasn't very performant.
Want to merge this in anyways to see what happens on a sitelord site
* Moved some methods around and added `_` to names for consistency with brightspaceui/core work (Still more to do to get consistent)

US113508 Awards Dialog

---

src/components/awards-leaderboard-ui.js

http://design.d2l/patterns/skeleton-loading/

US114065 Skeleton placeholder

---

src/components/award-issued.js
src/components/leaderboard-row.js

US114085 Add Responsiveness to widget

---

src/components/award-issued.js
src/components/awards-leaderboard-ui.js
src/components/leaderboard-row.js

https://app.zeplin.io/project/5e5e8d0faf422b653ba8422b/screen/5e5ebe13745699768603c76f
Updates to padding and font size

Cleanup styling as per Zeplin designs

---

src/components/award-issued.js
src/components/leaderboard-row.js
src/constants/constants.js

* Sizes to constants file for calculation purposes

Get badges displayed to shrink with smaller widget and font update

---

src/components/awards-leaderboard-ui.js

Did this to help screenreader
--Checking with design if this is necessary

US114065 Skeleton Aria Loading

---

src/components/awards-leaderboard-ui.js

* Also make the logged in user only display once

US114249 Make logged in user's info sticky to bottom

---

lang/en.json
src/components/awards-leaderboard-ui.js

* It will display empty if no items returned in list, or if no users in the list have any awards

US114296 Add checks to display empty state

---

src/components/award-issued.js
src/components/awards-leaderboard-ui.js
src/components/leaderboard-row.js
src/mixins/base-mixin.js

Full Screen View with RTL
Mobile View with RTL

US115035 RTL

---

lang/en.json
src/components/award-issued.js
src/components/awards-leaderboard-ui.js
src/components/leaderboard-row.js

Some accessibility changes
* Add aria tag
* Add alt tags (empty for empty image)

US115049 Some Accessibility

---

src/components/leaderboard-row.js

* Modelled this after Brightspace/google-calendar-widget-ui#122
* Compare new values to old values to see if the component needs to be updated

Update resize aware

---

src/components/award-details.js
src/components/award-issued.js
src/components/awards-leaderboard-ui.js
src/components/leaderboard-row.js

* Sort functions same way as our standard
* Re-order the class styles

Reorder items

---

src/components/award-details.js
src/components/leaderboard-row.js

* Set it to have ellipsis for text overflow
* Align credit/award count to be vertically centered

Fix styling of long names in full mode

---

src/components/awards-leaderboard-ui.js
src/components/leaderboard-row.js

* Force the rank circle to always be a circle - by number of pixels.
* Only have a scrollbar when needed

Styling Refining

---

src/components/awards-leaderboard-ui.js
src/components/leaderboard-row.js

* This will help with performance and not expose all the data in the DOM - Thank you @depowell

Set data to hidden and don't stringify

---

src/components/leaderboard-row.js

Fixing view of long names in medium view
Thank you @depowell-D2L for all your help on this one!

Styling long names

---

src/components/leaderboard-row.js

* Initially I kept the code the same so that it'd be easier to merge them together again if needed but I don't see that happening

Remove all if statements and update the code used for rendering

---

src/components/leaderboard-row.js

* Changing the div for names to be a Flex box with centered items caused ellipsis to not display
* Line-height was causing the name not to be centered - Line height only needed for cases when it needed to flow onto second line
-- If we can solve issue with the badges flowing out of view, we could do a white-space: nowrap

Ellipsis went missing (bring back ellipsis)

---

src/components/award-details.js

* Also added some some space between the labels in dialog
--> Ignore whitespace

DE39390 Fix image resizing in dialog for smaller screen sizes

---

test/awards-leaderboard-ui-tests.html

Can review with hiding whitespace

Fix tabbing in tests and remove unused variables

---

src/components/award-issued.js
src/components/leaderboard-row.js

* Hoping this will help with screenreaders

US115049 Move award buttons into a list

---

src/components/leaderboard-row.js

* It was cutting off hte item below it

Fix position of panel

---

package.json

There was still one more setting that prevented even admins from committing to `master`. I've adjusted it, so hopefully this one works!

fixing version

---

package.json

This is mainly just an excuse for me to try out the release changes from my previous PR.

Clean-up lint commands

---

.travis.yml

This will hopefully bring back the nuber of changes since master comment on the release page which is sometimes useful to do comparisons.

Add target_commitish

---

.github/labels.yml
.github/workflows/sync-labels.yml

Add declarative labels

---

.github/workflows/sync-labels.yml

Can't use self hosted runners since this repo is public.

Fix label sync

---

.github/labels.yml

This reverts commit 4a7ebe683d2bb58614a747574082b697435695b5, reversing
changes made to b33ebdf23080c7b0ecd6cc57acf7c2220ca022b4.

Revert "Merge pull request #95 from Brightspace/depowell/adjust-color"

---

src/components/leaderboard-row.js

Here is the fix.
Tested in browser here the screenshot:

Fix the leaderboard list.

---

.github/dependabot.yml

This is until issues are adressed

Add brightspace UI core to dependabot ignore list

---

src/components/leaderboard-row.js

Thanks @devpow112 for the help!
https://github.com/Brightspace/google-calendar-widget-ui/blob/master/src/components/google-calendar-event.js#L386

DE39308 Add hover text when name is long

---

src/components/leaderboard-row.js

* To display hover text if the user's name is longer than displayed

Add mouse enter for non-mobile view
